-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 10:56:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `classe_UNIQUE` (`classe` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `original` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  `sinopse` TEXT NOT NULL,
  `imagem` VARCHAR(20) NOT NULL,
  `ativo` ENUM('Sim', 'Não') NOT NULL,
  `classe_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_filme_classe_idx` (`classe_id` ASC),
  INDEX `fk_filme_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_filme_classe`
    FOREIGN KEY (`classe_id`)
    REFERENCES `classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `telefone` VARCHAR(17) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ativo` ENUM('Sim', 'Não') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `cliente_id` INT NOT NULL,
  `status` ENUM('Pago', 'A Pagar') NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locacao_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_locacao_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_locacao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filme_locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filme_locacao` (
  `filme_id` INT NOT NULL,
  `locacao_id` INT NOT NULL,
  `datadevolucao` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` ENUM('Locado', 'Devolvido') NOT NULL,
  `devolucao` DATE NULL,
  PRIMARY KEY (`filme_id`, `locacao_id`),
  INDEX `fk_filme_has_locacao_locacao1_idx` (`locacao_id` ASC),
  INDEX `fk_filme_has_locacao_filme1_idx` (`filme_id` ASC),
  CONSTRAINT `fk_filme_has_locacao_filme1`
    FOREIGN KEY (`filme_id`)
    REFERENCES `filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_locacao_locacao1`
    FOREIGN KEY (`locacao_id`)
    REFERENCES `locacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
